apiVersion: v1
kind: Service
metadata:
  labels:
  name: spring-web-k8s-svc
  namespace: default
spec:
  ports:
  - appProtocol: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app-name: spring-web-routing
  type: LoadBalancer

